openapi: 3.0.0
info:
  title: REST API
  version: '1.0'
  contact:
    name: Bham Urban Obs Team
    url: 'https://birminghamurbanobservatory.com/contact/'
servers:
  - url: 'https://api.birminghamurbanobservatory.com'
paths:
  /sensors:
    get:
      summary: Get Sensors
      tags:
        - sensors
      responses:
        '200':
          description: OK
      operationId: get-sensors
components:
  schemas: {}
