openapi: 3.0.0
info:
  title: REST API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /sensors:
    get:
      summary: Get Sensors
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-sensors
components:
  schemas: {}
